import { describe, it, expect } from 'vitest'
import { applyEvent } from '../chat/applyEvent'
import type { ChatItem, ClaudeEvent } from '../types'

const assistantEvt = (content: object[], raw: unknown = {}): ClaudeEvent =>
  ({ kind: 'assistant', message: { role: 'assistant', content }, raw }) as ClaudeEvent

describe('applyEvent', () => {
  it('texto do assistente vira assistant_text', () => {
    const out = applyEvent([], assistantEvt([{ type: 'text', text: 'olá!' }]))
    expect(out).toEqual([{ kind: 'assistant_text', text: 'olá!' }])
  })

  it('thinking vira item thinking', () => {
    const out = applyEvent([], assistantEvt([{ type: 'thinking', thinking: 'hmm' }]))
    expect(out).toEqual([{ kind: 'thinking', text: 'hmm' }])
  })

  it('tool_use vira tool_call e tool_result preenche o resultado', () => {
    let items: ChatItem[] = []
    items = applyEvent(items, assistantEvt([{ type: 'tool_use', id: 't1', name: 'Bash', input: { command: 'ls' } }]))
    expect(items[0]).toMatchObject({ kind: 'tool_call', id: 't1', name: 'Bash' })
    items = applyEvent(items, {
      kind: 'user',
      message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't1', content: 'arquivos...' }] },
      raw: {},
    } as ClaudeEvent)
    expect(items[0]).toMatchObject({ kind: 'tool_call', id: 't1', result: 'arquivos...' })
  })

  it('user com texto (histórico) vira user_text', () => {
    const out = applyEvent([], {
      kind: 'user',
      message: { role: 'user', content: [{ type: 'text', text: 'faça X' }] },
      raw: {},
    } as ClaudeEvent)
    expect(out).toEqual([{ kind: 'user_text', text: 'faça X' }])
  })

  it('result não adiciona nada ao chat (sem separador de turno)', () => {
    const prev = [{ kind: 'assistant_text', text: 'oi' }] as any
    const out = applyEvent(prev, { kind: 'result', subtype: 'success', isError: false, resultText: 'ok', costUsd: 0.01, raw: {} } as ClaudeEvent)
    expect(out).toEqual(prev)
  })

  it('init, system e raw são ignorados', () => {
    for (const evt of [
      { kind: 'init', sessionId: 's', model: 'm', raw: {} },
      { kind: 'system', subtype: 'thinking_tokens', raw: {} },
      { kind: 'raw', raw: {} },
    ] as ClaudeEvent[]) {
      expect(applyEvent([], evt)).toEqual([])
    }
  })

  it('evento assistant com parent_tool_use_id marca itens como fromSubagent', () => {
    const out = applyEvent(
      [],
      assistantEvt([{ type: 'text', text: 'trabalho do subagente' }], { parent_tool_use_id: 'toolu_x' }),
    )
    expect(out).toEqual([{ kind: 'assistant_text', text: 'trabalho do subagente', fromSubagent: true }])
  })

  it('evento assistant sem parent_tool_use_id não marca fromSubagent', () => {
    const out = applyEvent([], assistantEvt([{ type: 'text', text: 'olá!' }]))
    expect(out).toEqual([{ kind: 'assistant_text', text: 'olá!' }])
    expect((out[0] as any).fromSubagent).toBeFalsy()
  })

  it('tool_use dentro de um evento assistant de subagente vira tool_call com fromSubagent', () => {
    const out = applyEvent(
      [],
      assistantEvt(
        [{ type: 'tool_use', id: 't1', name: 'Bash', input: { command: 'ls' } }],
        { parent_tool_use_id: 'toolu_x' },
      ),
    )
    expect(out[0]).toMatchObject({ kind: 'tool_call', id: 't1', name: 'Bash', fromSubagent: true })
  })

  it('tool_result com is_error marca o tool_call como falho', () => {
    let items: ChatItem[] = []
    items = applyEvent(items, assistantEvt([{ type: 'tool_use', id: 't9', name: 'Bash', input: { command: 'x' } }]))
    items = applyEvent(items, {
      kind: 'user',
      message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't9', content: 'comando falhou', is_error: true }] },
      raw: {},
    } as ClaudeEvent)
    expect(items[0]).toMatchObject({ kind: 'tool_call', id: 't9', result: 'comando falhou', isError: true })
  })
})

describe('mensagens de sistema/terminal do lado do usuário (tags cruas do transcript)', () => {
  const userEvt = (text: string): ClaudeEvent =>
    ({ kind: 'user', message: { role: 'user', content: [{ type: 'text', text }] }, raw: {} }) as ClaudeEvent

  it('caveat de comando local é descartado por inteiro', () => {
    const out = applyEvent([], userEvt(
      '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>',
    ))
    expect(out).toEqual([])
  })

  it('slash command (/exit) vira chip local_command', () => {
    const out = applyEvent([], userEvt(
      '<command-name>/exit</command-name>\n            <command-message>exit</command-message>\n            <command-args></command-args>',
    ))
    expect(out).toEqual([{ kind: 'local_command', command: '/exit' }])
  })

  it('slash command com args preserva os args', () => {
    const out = applyEvent([], userEvt(
      '<command-name>/model</command-name><command-message>model</command-message><command-args>opus</command-args>',
    ))
    expect(out).toEqual([{ kind: 'local_command', command: '/model', args: 'opus' }])
  })

  it('stdout de comando local vira command_output; vazio é descartado', () => {
    const out = applyEvent([], userEvt('<local-command-stdout>Catch you later!</local-command-stdout>'))
    expect(out).toEqual([{ kind: 'command_output', text: 'Catch you later!' }])
    expect(applyEvent([], userEvt('<local-command-stdout></local-command-stdout>'))).toEqual([])
  })

  it('stderr vira command_output com isError', () => {
    const out = applyEvent([], userEvt('<local-command-stderr>deu ruim</local-command-stderr>'))
    expect(out).toEqual([{ kind: 'command_output', text: 'deu ruim', isError: true }])
  })

  it('texto real + task-notification na mesma mensagem: user_text limpo + system_note com o summary', () => {
    const out = applyEvent([], userEvt(
      'Segue um outro exemplo:\n<task-notification>\n<task-id>bdj5ujof6</task-id>\n<status>completed</status>\n<summary>Background command "Confirma 2 ticks" completed (exit code 0)</summary>\n</task-notification>',
    ))
    expect(out).toEqual([
      { kind: 'user_text', text: 'Segue um outro exemplo:' },
      { kind: 'system_note', text: 'Background command "Confirma 2 ticks" completed (exit code 0)' },
    ])
  })

  it('system-reminder é removido do texto; mensagem só de reminder some', () => {
    const out = applyEvent([], userEvt('minha pergunta real<system-reminder>lembrete interno do harness</system-reminder>'))
    expect(out).toEqual([{ kind: 'user_text', text: 'minha pergunta real' }])
    expect(applyEvent([], userEvt('<system-reminder>só lembrete</system-reminder>'))).toEqual([])
  })

  it('texto comum do usuário continua passando intacto', () => {
    const out = applyEvent([], userEvt('mensagem normal sem tags'))
    expect(out).toEqual([{ kind: 'user_text', text: 'mensagem normal sem tags' }])
  })
})

describe('mensagens de usuário geradas pela engine (isMeta/isCompactSummary)', () => {
  it('user com raw.isMeta vira user_text com fromEngine', () => {
    const items = applyEvent([], {
      kind: 'user',
      message: { role: 'user', content: [{ type: 'text', text: 'conteúdo injetado pela engine' }] },
      raw: { type: 'user', isMeta: true },
    } as never)
    expect(items).toEqual([{ kind: 'user_text', text: 'conteúdo injetado pela engine', fromEngine: true }])
  })

  it('user com raw.isCompactSummary vira user_text com fromEngine', () => {
    const items = applyEvent([], {
      kind: 'user',
      message: { role: 'user', content: 'This session is being continued…' },
      raw: { type: 'user', isCompactSummary: true },
    } as never)
    expect(items).toEqual([{ kind: 'user_text', text: 'This session is being continued…', fromEngine: true }])
  })

  it('user normal NÃO ganha fromEngine', () => {
    const items = applyEvent([], {
      kind: 'user',
      message: { role: 'user', content: 'oi' },
      raw: { type: 'user' },
    } as never)
    expect(items).toEqual([{ kind: 'user_text', text: 'oi' }])
  })
})
